# Generated by Django 4.0.3 on 2022-03-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='url',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
